### ISSUE TITLE
[Docs]: Maybe we could have a page of overview for the flavor,

### ISSUE THREAD

**Issue by 6za** [konstructio/kubefirst-docs#18]
### What type of suggestions?

Missing Information

### What page is concerned?

http://localhost:8000/kubefirst/local/github-repositories/#repository-summary

### What is the issue?

J - Maybe we could have a page of overview for the flavor, so info like this could live there:
http://localhost:8000/kubefirst/local/github-repositories/#repository-summary
![image](https://user-images.githubusercontent.com/53096417/211550115-80da0719-3e2d-475b-a54f-ae623c59261c.png)

Sample: 
```md
# Kubefirst local

- It is a local setup of what we offer on the cloud provisioning tool
- with a gitops repo for guiding your gitops setup
- with metaphor-frontend as demo application
- Atlantis integration
...
```

Then link to the major journey.
- Install
- Explore
- Destroy

Also, the "this overview of the repos" maybe it would fit better in a table. 

Actions: 
- [ ] Create an overview page for aws-github
- [ ] Create an overview page for aws-gitlab
- [ ] Create an overview page for local

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 6za** [comment]
Related to:
- kubefirst/kubefirst#1071

Adding to this: 
B - Should we have overview pages for major blocks of pages in the docs?
it seems a bit weird that we click and nothing appears on the side.. it may make some people lost on where to start. Is it top to bottom? Is it install?

From: @fharper
B: I totally agree, first thing I found weird when I tried Kubefirst during my interview process. I thought it was a limitation of mkdocs, but it may not be. In any cases, when we move to Docusaurus, it will be possible to do so. Can you also create an issue for that as it’s important, really doesn’t give a good experience as you mentioned!

**Comment by converge** [comment]
agreed on slack to decouple it from 1.11.0
