### ISSUE TITLE
[Docs]: document how end to end tests can be executed

### ISSUE THREAD

**Issue by converge** [konstructio/kubefirst-docs#21]
### What type of suggestions?

Missing Information

### What is the issue?

Some end to end tests were introduced, it will be beneficial to document how to and when call them.

AC1: check if current admin-github.tf file is being reflected in the docs
AC2: there is a developer documentation describing how and when to run the tests

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
For now, https://github.com/kubefirst/kubefirst/tree/main/tests is enough. We'll revisit when more effort will be done on the testing side of kubefirst.
