### ISSUE TITLE
Add clarity on last deprovisioning step when doing manually

### ISSUE THREAD

**Issue by fharper** [konstructio/kubefirst-docs#322]
### What type of suggestions?

Missing Information

### What page is concerned?

https://docs.kubefirst.io/civo/deprovision

### What version of the docs?

2.1

### What is the issue?

If you finish the destroying steps done manually with terraform and al, once you reach that point, it's not clear if you're done or not. We should just add a quick conclusion, or confirming it was the last steps like we do for the destroy description for k3d right after.

<img width="1009" alt="CleanShot 2023-06-09 at 16 04 21@2x" src="https://github.com/kubefirst/docs/assets/1170989/e5efef93-3d81-400b-a9ea-236e8d5444dd">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by echoboomer** [comment]
We cannot do this here. Terraform is run independently of kubefirst in this case and we do not have the ability to provide any context.

Also, once you've destroyed the resources in terraform, there shouldn't be anything left in relation to the cluster. We may need to add some information about cleaning up things like state storage.

**Comment by fharper** [comment]
We can provide context as you wrote it yourself "Also, once you've destroyed the resources in terraform, there shouldn't be anything left in relation to the cluster. ". It can be something as simple as: if the previous Terraform commands ran successfully, the deprovisioning of your cluster created with kubefirst is finished. Just to finish the section. It's not a technical request, just making the documentation clearer.

**Comment by echoboomer** [comment]
Right. I took this as messaging from the app versus docs improvements. Disregard. Docs improvements are the way to go.

**Comment by fharper** [comment]
No worries, this repos only have docs issues :)
