### ISSUE TITLE
[Docs]: how to build Kubefirst with Gitlab flavor

### ISSUE THREAD

**Issue by marinhojess** [konstructio/kubefirst-docs#43]
Documentation for current build of kubefirst with Gitlab flavor:

### Build and Install

Required flags:

```
export KUBEFIRST_GITOPS_BRANCH='main' --> can be replaced by the --gitops-branch flag in the init command.
export KUBEFIRST_METAPHOR_BRANCH='main' --> can be replaced by the --metaphor-branch flag in the init command.
export KUBEFIRST_AWS_NODES_SPOT='true' --> can be replaced by the --aws-nodes-spot flag in the init command.
```

Optional flags:

```
export KUBEFIRST_S3_SUFFIX='...' --> can be replaced by the --s3-suffix flag in the init command.
export KUBEFIRST_CLUSTER_NAME='...' --> can be replaced by the --cluster-name flag in the init command.
```

_PS: The following commands must be run from the Kubefirst root directory._

To build the application: 
```
go build -ldflags="-X github.com/kubefirst/kubefirst/configs.K1Version=1.10.1" .
```

To run the installer with the above environment variables already set:

```
./kubefirst init --profile default --cloud aws --region $REGION \
    --admin-email $EMAIL --hosted-zone-name $HOSTED_ZONE --git-provider gitlab
```
To run the installer without the above environment variables:
```
./kubefirst init --profile default --cloud aws --region $REGION \
    --admin-email $EMAIL --hosted-zone-name $HOSTED_ZONE --aws-nodes-spot \
    --cluster-name $CLUSTER_NAME --s3-suffix $S3_SUFFIX --gitops-branch $GITOPS_BRANCH --metaphor-branch $METAPHOR_BRANCH --git-provider gitlab
```

To create kubefirst witth console

```
./kubefirst cluster create --enable-console
```

### SSL Backup

After a few minutes of creating the cluster, it is possible to backup the certificates using the following command:

```./kubefirst backupSSL```

After executing this command, an S3 bucket will be created in AWS with the name k1-$HOSTED_ZONE_NAME:

![image](https://user-images.githubusercontent.com/19623668/189911700-71cb2a39-0fbd-47fd-9a7f-3bf405944c7f.png)
![image](https://user-images.githubusercontent.com/19623668/189911848-16409969-e823-4c28-8283-f6ea68a80d49.png)
![image](https://user-images.githubusercontent.com/19623668/189912026-fc420f6b-74ac-41f2-8469-2ac1e0884709.png)
![image](https://user-images.githubusercontent.com/19623668/189912152-b0c1c389-dd87-4887-a0c0-e7477ace081b.png)

On the next install, the init command will look for an existing bucket in the cloud and reuse the certificate backups.

### Destroy and Clean

To destroy all resources created by **_kubefirst create cluster_**:

```
./kubefirst cluster destroy
```

To destroy the paths $HOME/.k1, $HOME/.kubefirst and buckets created by **_kubefirst init_**:

```
./kubefirst clean --destroy-buckets --destroy-confirm 
```
To destroy only the paths $HOME/.k1 and $HOME/.kubefirst:

```
./kubefirst clean
```

**Comment by fharper** [comment]
@marinhojess: are you planning to update the documentation yourself or do you want me to use what you wrote and do it myself?
