### ISSUE TITLE
Automatically label issues based on the suggestion type selection

### ISSUE THREAD

**Issue by fharper** [konstructio/kubefirst-docs#482]
### What type of suggestions?

Something's not working

### What version of the docs?

N/A

### What is the issue?

Automatically label issues based on the suggestion type selection.

Maybe using this GitHub Action https://github.com/github/issue-labeler

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
I wanted to use that to triage more easily what needs to be done, but I'll leave it to you @konstructcarrie to decide if it's something useful for you or not :)

**Comment by konstructcarrie** [comment]
the only issue I see here is that issues should still be reviewed to see that 
- it has a label if none was automatically applied
- the label is correct since just using the words "urgent" or "critical" may not be an accurate way to define a P0
