### ISSUE TITLE
Explain how to change kbot password

### ISSUE THREAD

**Issue by fharper** [konstructio/kubefirst-docs#638]
### What type of suggestions?

Missing Information

### What page is concerned?

https://docs.kubefirst.io/aws/explore/vault

### What version of the docs?

2.3+

### What is the issue?

Explain how to change `kbot` password in Vault.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johndietz** [comment]
for awareness
https://docs.kubefirst.io/common/vault/#how-can-i-change-my-users-password

**Comment by fharper** [comment]
Oh, I didn't remember it was there!

I'll just point people there from the getting started page, thanks.
