### ISSUE TITLE
kubefirst docs content needs stronger identification of kubefirst pro

### ISSUE THREAD

**Issue by johndietz** [konstructio/kubefirst-docs#714]
the kubefirst open source platform and the kubefirst pro user interface need stronger lines of delineation throughout our docs.

gitlab has a similar problem, and use a [PRO] label in their docs when they're talking about pro stuff. i would be in favor of a similar technique, but open to interpretation to produce the best user experience

**Comment by fharper** [comment]
As soon as we have clear information on what will be in the PRO edition as I think it changed since our initial discussion, please update this issue, and I will update the docs.

**Comment by fharper** [comment]
So for now the pro tier is only about paying for additional clusters after the third one. So no need for a big update as we should point to the website pricing page (not online yet) for more information, but it need to be clear in the docs. We can discuss more where we should put that info.

**Comment by konstructcarrie** [comment]
This issue is being solved with the creation of a dedicated site.
