### ISSUE TITLE
Fix: URL for Slack in Footer (Chrome)

### ISSUE THREAD

**Issue by konstructcarrie** [konstructio/kubefirst-docs#780]
### What type of suggestions?

Something's not working

### What page is concerned?

https://kubefirst.konstruct.io/docs/

### What version of the docs?

2.6, 2.5

### What is the issue?

From the following base URL https://kubefirst.konstruct.io/docs/

If I click on the Slack link at the footer
![image](https://github.com/user-attachments/assets/2c9f7363-ca02-4907-a824-63148efd2ad7)

**I get a 404 - in Chrome.** 

When I tried this is in Duck Duck Go it loaded the Slack path. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
I finally was able to replicate on a new browser.

It's weird caused the footer URL is good in the docs

![CleanShot 2024-10-07 at 15 01 58@2x](https://github.com/user-attachments/assets/7ef5c821-a670-4287-9c7f-7568016ddf27)

**Comment by fharper** [comment]
It's not a P0 in the sense that everything is on fire, but this is the main way for our users to get help, so super important!

**Comment by konstructcarrie** [comment]
This should be resolved with this PR https://github.com/konstructio/kubefirst-docs/pull/840
