### ISSUE TITLE
AWS multi-account support

### ISSUE THREAD

**Issue by fharper** [konstructio/kubefirst-docs#793]
### What type of suggestions?

Missing Information

### What version of the docs?

2.6+

### What is the issue?

Add information about multi-account support for AWS. Probably need to be in the `Overview` page as summary of what the AWS support means, and somewhere else in the docs to details how to use it.

I also believe that kubefirst features should be in parity in all clouds to give the same experience to everyone no matter which cloud they are using, but the reality is that it's not always possible: either because of engineering time we start with specific cloud and release right away, specific needs that have to be fulfilled right away or sometimes it's not a possibility cause it's related to a specific feature of a cloud. To help the users navigate toward all these, I have a known limitation section on all main cloud pages listing what is different from the usual experience, like at https://kubefirst.konstruct.io/docs/aws/overview#known-limitations . I usually approach this as "what is missing in cloud X compared to the other clouds" vs "what is available that is not elsewhere" as I feel it limit the confusion is someone saw the multi-account feature and look for it in Google or Civo. Could be good to also highlight this missing feature on other clouds.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by konstructcarrie** [comment]
AWS docs have been updated to:
- Remove note about workloads not being supported
- Added a section under Advanced about Multi-account
