### ISSUE TITLE
Workload clusters now available in AWS

### ISSUE THREAD

**Issue by fharper** [konstructio/kubefirst-docs#794]
### What type of suggestions?

Wrong Information

### What page is concerned?

https://kubefirst.konstruct.io/docs/aws/overview#aws-specific

### What version of the docs?

2.6+

### What is the issue?

Workload clusters are now available in AWS so we need to remove the known limitation about this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by konstructcarrie** [comment]
This has been updated.  https://github.com/konstructio/kubefirst-docs/pull/841
