### ISSUE TITLE
Workload clusters now available in Google Cloud

### ISSUE THREAD

**Issue by fharper** [konstructio/kubefirst-docs#795]
### What type of suggestions?

Wrong Information

### What page is concerned?

https://kubefirst.konstruct.io/docs/gcp/overview/#google-cloud-specific

### What version of the docs?

2.6+

### What is the issue?

Workload clusters are now available in Google Cloud so we need to remove the known limitation about this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by konstructcarrie** [comment]
@fharper  Does this update require anything other than deleting the line here: https://kubefirst.konstruct.io/docs/gcp/overview/#google-cloud-specific ?

**Comment by fharper** [comment]
No, just that for this issue.
