### ISSUE TITLE
Add information on how to use add-ons on gitops template

### ISSUE THREAD

**Issue by 6za** [konstructio/kubefirst-docs#81]
# Overview 

- 1.9.0 will introduce the possibility of using addons on our templates repo

Sample: 
https://github.com/kubefirst/gitops-template/blob/main/registry/argo-github.yaml#L10

The goal of this ticket, to create some documentation and samples how the community can bring their add-ons to the template repo to be used on desired scenarios.  

Example of add-ons:
- spark-ready enabled namespaces
- datadog ready install 
- github/gitlab selection

**Comment by johndietz** [comment]
this issue has been closed due to the introduction of the gitops-catalog in 3.1 which is our new preferred way to add content to the kubefirst platform after provisioning.
