### ISSUE TITLE
Correct k3d docs to reference only a single cluster instead of msultiple workload cluster

### ISSUE THREAD

**Issue by ikegentz** [konstructio/kubefirst-docs#844]
### What type of suggestions?

Wrong Information

### What page is concerned?

https://kubefirst.konstruct.io/docs/k3d/overview

### What version of the docs?

2.3+

### What is the issue?

The <= 2.2 version of the k3d quickstart correctly stated that:

> The k3d provisioning process will:
 Create a multinode k3d Kubernetes cluster on your localhost.

This is indeed what currently happens. I actually just ran the k3d setup as of 12/8/2024 (kubefirst v2.7) and you can see that there is a single _cluster_ created, but multiple `k3s` _nodes_ **are** created to run the workloads across `development`/`staging`/`production` _namespaces_

The issue however, is that in the 2.3+ version of the documentation, this second bulletpoint is now included, which is not correct.

> Create three virtual workload clusters for each default environment (development, staging & production).

I spent about 30 minutes poking around at my local setup trying to find the "workload clusters", until I came across this [slack thread](https://konstructio.slack.com/archives/C03U34WJ7FW/p1732801388367319) confirming my suspicions that there is a single cluster

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ikegentz** [comment]
I took a quick peek at a PR for this, however it looks like this verbiage is actually coming from the `_provision-process.mdx` template which is used in the "Overview" page for each cloud, so may be a bit of a refactor to _exclude_ just one cloud (`k3d`). 

Is it correct to say that `k3d` is the _only_ cloud for which the statement "Creates three virtual workload clusters..." is false? May influence a refactor

**Comment by fharper** [comment]
@ikegentz: thanks for reporting this issue and working on a PR. It's somewhat true as it is not on available on all beta clouds **yet** (but it will be mentioned in the limitation section of their overview page if it's not available), but it's also true that once all clouds are out of beta, k3d is the only one that won't have workload clusters.

Once you are ready for a PR, our Technical Writer @konstructcarrie will review it, thanks. Or let us know if you prefer not to move forward with the PR, no stress, this issue is already a great contribution so we know what we have to fix :)

**Comment by konstructcarrie** [comment]
Removed the incorrect Overview guidance from our current docs.

**Comment by fharper** [comment]
@ikegentz: sorry we didn't wait for the PR you were working on. Still, contact me on our [Slack community](https://konstruct.io/slack) (I'm Fred): I would like you send you some swag as a token of our appreciation!

**Comment by ikegentz** [comment]
Haha no worries, I hadn't taken time to work on it yet so nothing time lost on my end. Thanks for getting this clarified in the docs!

**Comment by ikegentz** [comment]
Thanks for hopping on this so fast! I did take a look at the PR; I guess as someone using Kubefirst for the first time, I actually really like the original verbiage:

>  Create three virtual workload clusters for each default environment (development, staging & production). 

I think that is clear about what all gets created, so IMO it is a net loss to remove it from _all_ references in docs. I created a PR that instead updates only the `k3d` pages to hopefully make it more clear that `k3d` is the only one that's different.

**Comment by fharper** [comment]
@ikegentz: the change @konstructcarrie did is correct. There is a difference between what we discussed and what the docs was saying. I realized I may nt have formulated it correctly, but the point I wanted to make is that only public cloud support workload clusters (and some in beta), but not k3d. We also don't create three virtual clusters by default anymore, so it's why we removed this sentence from the docs. Maybe a better way would have been to replace it with something like "possibility to create workload clusters" in the overview page, but I'll defer to @konstructcarrie, our Technical Writer, to follow up on this.

**Comment by ikegentz** [comment]
> @ikegentz: the change @konstructcarrie did is correct. There is a difference between what we discussed and what the docs was saying. I realized I may nt have formulated it correctly, but the point I wanted to make is that only public cloud support workload clusters (and some in beta), but not k3d. We also don't create three virtual clusters by default anymore, so it's why we removed this sentence from the docs. Maybe a better way would have been to replace it with something like "possibility to create workload clusters" in the overview page, but I'll defer to @konstructcarrie, our Technical Writer, to follow up on this.

Thanks for the clarification @fharper, that makes more sense now. Happy to amend that PR if there is some other phrasing is useful or whatnot. I like at least mentioning the workload clusters since that can have an impact on cloud spend and it's useful to know the overall infrastructure footprint that's being created

**Comment by fharper** [comment]
The cloud spends will only increase if the user manually create a workload cluster, or do any other actions that require more cloud resources, so it's not by default. As I mentioned, we used to create three workload clusters by default, but we don't anymore so there is nothing else to add to the documentation. The overview section in each cloud is specific to what Kubefirst do automatically, not everything else you can do with the platform, so unfortunately, I think your PR isn't needed at all. Thanks again for proposing and helping 🙌

I always suggest that people discuss with us before doing a substantial PR like yours to prevent someone working on something that may not be needed, sorry about that. Check https://github.com/konstructio/kubefirst-docs/blob/main/CONTRIBUTING.md#ways-to-contribute for more information :)
